name: SpaceWarp Builder

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        run_args: ["" , "-r"]
        zip_pattern: ["SpaceWarp-Debug*.zip", "SpaceWarp-Release*.zip"]
        artifact_name: ["SpaceWarpDebug", "SpaceWarpRelease"]
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Run Python Script
        run: sudo python builder.py ${{ matrix.run_args }} 
        # I'm sure running it in sudo will cause NO issues what so ever.
        
      - name: Find Debug Zip
        id: find-zip
        run: echo "::set-output name=zip::$(ls -1 build/${{ matrix.zip_pattern }} | head -n 1)"
        # Yeah... this is a little cursed I can't lie.

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ artifact_name }}
          path: ${{ steps.find-zip.outputs.zip }}
        
