name: SpaceWarp Builder

on:
  push:
    branches:
      - main  # Replace with your desired branch name
  pull_request:
    branches:
      - main  # Replace with your desired branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Python Script
        run: sudo python builder.py # I'm sure running it in sudo will cause NO issues what so ever.
        
      - name: Find Debug Zip
        id: find-zip
        run: echo "::set-output name=zip::$(ls -1 build/SpaceWarp-Debug*.zip | head -n 1)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SpaceWarp Artifact
          path: ${{ steps.find-zip.outputs.zip }}
        
