name: Nightly Builds and Alpha Releases

on:
  push:
    branches: [ "main" ] # Will make this a chron job on release.

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List Tags
        run: git tag
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Get Latest Version
        id: get_version
        run: |
          version_number=$(echo $(git describe --tags --match "spacewarp*" --abbrev=0) | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+")
          echo "VERSION_NUMBER=$version_number" >> $GITHUB_ENV

      - name: Run Python Script
        run: sudo python builder.py -r

      - name: Find Zip
        id: find-zip
        run: |
          echo "artifact_name=SpaceWarpRelease.zip" >> $GITHUB_ENV
          echo "zip=$(ls -1 build/SpaceWarp-Release*.zip | head -n 1)" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.zip }}

      - name: Create Alpha Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: "spacewarp-${{ env.VERSION_NUMBER }}-(commit hash)"
          release_name: "SpaceWarp ${{ env.VERSION_NUMBER }}-(commit hash)"
          draft: false
          prerelease: true
          body: |
            ## Changelog

            Add auto-generated changelog
  
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.zip }}
          asset_name: ${{ env.artifact_name }}
          asset_content_type: application/zip
