name: Publish NuGet Package

on:
  release:
    types: [ "published" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get Release Data
        run: |
          URL=$(wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq '.[0].upload_url' | tr -d \")
          echo "::set-output name=url::$URL"
