name: Publish NuGet Package

on:
  release:
    types: [ "published" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Download NuGet
        id: download-nuget
        run: |
          sudo curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      - name: Build the solution
        run: dotnet build "SpaceWarp.sln" -c Release

      - name: Extract current version
        id: get-version
        run: |
          version=$(jq -r '.version' plugin_template/BepInEx/plugins/SpaceWarp/swinfo.json)
          echo "Version is $version"
          echo "::set-output name=version::$version"
 
      - name: Upload Zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: $(wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq '.[0].upload_url' | tr -d \")
          asset_path: $(ls -1 dist/SpaceWarp-*.zip | head -n 1)
          asset_name: spacewarp-release-${{ steps.get-version.outputs.version }}.zip
          asset_content_type: application/zip
          
          

           
